#define GPU_MEM_START_ADDR 0x2000
#define KERNEL_LOAD_ADDR 0x10000

#define GPU_DRAM_SIZE (1 << 29) // 512MB

#define KERNEL_STACK_SIZE (1 << 22) // 8MB
#define KERNEL_TLS_SIZE (1 << 22) // 4MB

// all below offset by gpu mem start addr
#define KERNEL_HEADER_MEM_START_PC GPU_MEM_START_ADDR // [0:3], 4 bytes
#define KERNEL_HEADER_MEM_KERNEL_PC (KERNEL_HEADER_MEM_START_PC + 4) // [4:7], 4 bytes
#define KERNEL_HEADER_MEM_PARAMS_SZ (KERNEL_HEADER_MEM_KERNEL_PC + 4) // [8:11], 4 bytes
#define KERNEL_HEADER_MEM_BINARY_SZ (KERNEL_HEADER_MEM_PARAMS_SZ + 4) // [12:15], 4 bytes
#define KERNEL_HEADER_MEM_STACK_BASE_ADDR (KERNEL_HEADER_MEM_BINARY_SZ + 4) // [16:19], 4 bytes
#define KERNEL_HEADER_MEM_TLS_BASE_ADDR (KERNEL_HEADER_MEM_STACK_BASE_ADDR + 4) // [20:23], 4 bytes
#define KERNEL_HEADER_MEM_GRID_X (KERNEL_HEADER_MEM_TLS_BASE_ADDR + 4) // [24:27], 4 bytes
#define KERNEL_HEADER_MEM_GRID_Y (KERNEL_HEADER_MEM_GRID_X + 4) // [28:31], 4 bytes
#define KERNEL_HEADER_MEM_GRID_Z (KERNEL_HEADER_MEM_GRID_Y + 4) // [32:35], 4 bytes
#define KERNEL_HEADER_MEM_BLOCK_X (KERNEL_HEADER_MEM_GRID_Z + 4) // [36:39], 4 bytes
#define KERNEL_HEADER_MEM_BLOCK_Y (KERNEL_HEADER_MEM_BLOCK_X + 4) // [40:43], 4 bytes
#define KERNEL_HEADER_MEM_BLOCK_Z (KERNEL_HEADER_MEM_BLOCK_Y + 4) // [44:47], 4 bytes
#define KERNEL_HEADER_MEM_PRINTF_HOST_ADDR (KERNEL_HEADER_MEM_BLOCK_Z + 4) // [48:51], 4 bytes
#define KERNEL_HEADER_MEM_REGS_PER_THREAD (KERNEL_HEADER_MEM_BLOCK_Z + 4) // [52:52], 1 byte
#define KERNEL_HEADER_MEM_SMEM_PER_BLOCK (KERNEL_HEADER_MEM_REGS_PER_THREAD + 1) // [53:56], 4 bytes
#define KERNEL_HEADER_MEM_FLAGS (KERNEL_HEADER_MEM_SMEM_PER_BLOCK + 4) // [57:57], 1 byte
#define KERNEL_HEADER_MEM_PADDING ((KERNEL_HEADER_MEM_FLAGS + 1) & 3) // [58:59], 2 bytes of padding for 4 byte alignment
#define KERNEL_HEADER_MEM_END (KERNEL_HEADER_MEM_FLAGS + 1 + KERNEL_HEADER_MEM_PADDING) // [60] 
#define KERNEL_MEM_PARAMS_START KERNEL_HEADER_MEM_END // [60:60+PARAMS_SZ-1] PARAMS_SZ bytes

#define KERNEL_HEADER_BYTES 60
#define KERNEL_REGS_PER_THREAD 1
#define KERNEL_SMEM_PER_BLOCK 1
#define KERNEL_FLAGS 0
#define KERNEL_PRINTF_HOST_ADDR 0
#define KERNEL_RESERVED_U16 0

#define CSR_BLOCK_IDX_X 0xfc3
#define CSR_BLOCK_IDX_Y 0xfc4
#define CSR_BLOCK_IDX_Z 0xfc5
#define CSR_THREAD_IDX_X 0xfc6
#define CSR_THREAD_IDX_Y 0xfc7
#define CSR_THREAD_IDX_Z 0xfc8

#define IO_COUT 0xFF080000